auth: password
password: password
bind-addr: 0.0.0.0:1337
cert: /home/nonroot/certs/my.pem
cert-key: /home/nonroot/certs/my.key
disable-telemetry: true
extensions-dir: /app/code-server/config/extensions
user-data-dir: /app/code-server/config/data