name: base
channels:
  - conda-forge
  - nodefaults
dependencies:
  - ipykernel
  - jupyterlab>=4,<5
  - jupyter-marimo-proxy
  - mamba_gator
  - marimo
  - nb_conda_kernels
  - notebook>=7,<8
  - pip=23.3
  - pip:
      - ipyflow
      - ipyparallel
      - mitosheet